
// This code was generated by Dasha Playground.
// See README.md to start

const dasha = require("@dasha.ai/sdk");

const main = async () => {
	const app = await dasha.deploy("./app");
	await app.start({ concurrency: 10 });

	const sandbox = {
		tts: "dasha",
		stt: "default",
		endpoint: process.argv[2] ?? "",
		execute: async (input) => {
			const conv = app.createConversation(input);
			const channel = sandbox.endpoint !== "chat" ? "audio" : "text";

			if (channel === "audio") {
				conv.on("transcription", (log) => console.log(log));
			}

			if (channel === "text") {
				await dasha.chat.createConsoleChat(conv);
			}

			conv.audio.tts = sandbox.tts;
			conv.audio.stt = sandbox.stt;
			conv.audio.noiseVolume = 0;

			return await conv.execute({ channel });
		},
	};

	app.setExternal("console_log", (args, conv) => {
	  console.log(args);
	});
	
	await sandbox.execute({
	  phone: sandbox.endpoint,
	  name: "Peter"
	})
}

main();

